default: &default
  adapter: postgresql

development:
  <<: *default
  database: nightingale_development

test:
  <<: *default
  database: nightingale_test

production:
  <<: *default
  database: nightingale_production
