default: &default
  adapter: postgresql
  host: 0.0.0.0
  password: password

development:
  <<: *default
  database: nightingale_development

test:
  <<: *default
  database: nightingale_test

production:
  <<: *default
  database: nightingale_production
  username: postgres
  host: db
