default: &default
  adapter: postgresql
  host: 0.0.0.0
  password: password

development:
  <<: *default
  database: nightingale_development
  pool: 10
  timeout: 15000

test:
  <<: *default
  database: nightingale_test

production:
  <<: *default
  database: nightingale_production
  username: postgres
  host: db
