# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09300a0cb81942aa6012d938ef24a3b80d4d3873344189f96cbab8b01358b5f5350089287805b79f6d28dc4fb7b3522216a2d17e72419c03e3270a952a563026

test:
  secret_key_base: b883911bad210d4a245b32857ba8f4ff0cb836d87b6f92f0a4acc89fa7c0528479aa5d589bdbdfaddb51eca6b01e0dfe542774b22d2380d8a54783cedf5b81b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: connectathon19
